### ISSUE TITLE
生成的冰蝎，tomcat9中间件filter类型的内存马，无法注入

### ISSUE THREAD

**Issue by liuhengliang666** [pen4uin/java-memshell-generator-release#21]
![image](https://github.com/pen4uin/java-memshell-generator-release/assets/70633508/d1368dcf-76ce-4a6f-a666-4083eab9dbba)
![image](https://github.com/pen4uin/java-memshell-generator-release/assets/70633508/b027bfd3-66d8-48d8-bf9d-2cca4fad719b)

classnotFoundException：注入的内存马类名是找不到

**Comment by liuhengliang666** [comment]
使用的apache-tomcat-9.0.89

**Comment by liuhengliang666** [comment]
jdk是jdk1.8.0.132

**Comment by pen4uin** [comment]
### 验证注入器兼容性
1、环境
```yaml
version: '3'

services:
  java8-tomcat9.0.89:
    # Tomcat 9.0.20 JRE 1.8
    image: tomcat:9.0.89-jdk8
    container_name: java9089-tomcat
    ports:
      - "9090:8080"
    volumes:
      - ../code/web/NetworkUtils.jsp:/usr/local/tomcat/webapps/ROOT/NetworkUtils.jsp
    networks:
      - apps

networks:
  apps:
    driver: "bridge"
```

2、jmg 生成内存马
![Uploading image.png…]()
